### ISSUE TITLE
Add to Open VSX Registry

### ISSUE THREAD

**Issue by oierbravo** [Sorae/vscode-escoria#4]
Hi!
Could you plz add the extension the Open VSX Registry so it's available for VSCodium and others.
https://open-vsx.org/

Related documentation:
- https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Nice work by the way! soooo useful.
Thx!

**Comment by Sorae** [comment]
Hello @oierbravo 👋 

Thanks for the suggestion, it's actually a really nice idea and looking at the documentation you linked (really appreciated by the way) it does not look too much work to add this target in the release.

No promises on the timeline, but I'll have a deeper look at this during the week and will prepare the milestone.

Great to know that you're using this add-on! The repo has been collecting dust lately but let me know if you have suggestions to improve it. 
I know the Escoria team has been hard at work on the v4 and I'll probably have to release an update to support their new commands and keywords.

**Comment by oierbravo** [comment]
Sounds amazing!
They are indeed working hard.
Ill take a look to the actual v4 commands and your extension to see if something is missing, for now I don't miss any command.
Thanks!

**Comment by Sorae** [comment]
Hey @oierbravo,
I've just published `vscode-escoria` to Openvsx. It's the same build as the MS marketplace for now so it does not yet include your changes, but I'll be releasing the new version in the following days.

Can you confirm that you can see the extension on your end?

**Comment by oierbravo** [comment]
It works!🎉
I can find & install the extension.
Thx!!!
